### ISSUE TITLE
unknown infinite loop on legend creating functions 

### ISSUE THREAD

**Issue by muhammed-ajmal** [gulan28/covid19-viz#2]
I just got a simple idea that the code will help to create legends for selected features on selected dates, But I'm unclear why it create loop for one set of value, ie

- `Kottayam,59,59,0,0` this value creates the infinite loops for `i+=Math.floor((rmax - rmin)/5)`

- while `Kottayam,59,59,0,5` this value run the program without  any infinite loops `i+=Math.floor((rmax - rmin)/5)`

## Re-produce the error

**:- Check the live preview of this error at :-** http://covid19.serverless.social/covid19-viz/ 

- open the link
- open the console using inspect elements option 
- choose the date to 5-3-2020
- log the console
- soon the loop will crash your browser session

From the function `legend.update`
`for (var i=rmin; i<=rmax; i+=Math.floor((rmax - rmin)/5))`
`{`
`		intervals.push(i);`
`	} `

> the above  loop creates unknown infinite loop for the dataset from [Daily Buletin ](http://dhs.kerala.gov.in/wp-content/uploads/2020/03/bule_05032020.pdf) on 05-03-2020 for the value 5 ` i+=Math.floor((rmax - rmin)/5)` on while incrementing

# Observed changes:-
- ` i+=Math.floor((rmax - rmin)/5)` to ` i+=Math.floor((rmax - rmin)/4)`

> above will terminate the loop, but it will decrement the no.of legends

-  `i+=Math.floor((rmax - rmin)/5)` to ` i+=Math.floor((rmax - rmin)/6)`
> above will above will terminate the loop , but it will increment the no.of legends

- `rmax = d3.max(d, function(item){return parseInt(item[selected_feature])});`  to  `rmax=100`
>above will not create any loops, number of legends same as before, But, I think it will limit the legends at 100

**Final Assumptions** :- 
- So the problem exists somewhere at the value for `rmax`, (the limit for forloops) 
- at some instance, the rmax shoot the value to infinite

**Comment by gulan28** [comment]
rmax and rmin are calculated at these two lines
`		rmin = d3.min(d, function(item){return parseInt(item[selected_feature])});`
`		rmax = d3.max(d, function(item){return parseInt(item[selected_feature])}); `
Here `d` corresponds to data for a day and the anonymous function inside `d3.min` selects a `feature` namely total hospitalized/isolated/hospitalized today. (columns in the data)

I suspect that it's because rmax and rmin are both zeroes and this causes the bug. Will push a fix soon and you can test it afterwards.

**Comment by muhammed-ajmal** [comment]
![Screenshot from 2020-03-18 14-02-42](https://user-images.githubusercontent.com/28041916/76941130-7cfcc900-6921-11ea-91bf-b86587f25148.png)

issue still exists , check at http://covid19.serverless.social/covid19-viz/

**Comment by gulan28** [comment]
Can you check now ? Will keep the issue reopened until the fix has been verified.

**Comment by muhammed-ajmal** [comment]
Yep, Now it is working smoothly, so `Math.floor` was the issue :+1:
