### ISSUE TITLE
Not able to import pivot.json on Power BI

### ISSUE THREAD

**Issue by codename062** [gulan28/covid19-viz#5]
Not able to import pivot.json on Power BI

https://community.powerbi.com/t5/Desktop/We-found-extra-characters-at-the-end-of-JSON-input/td-p/20607
https://community.powerbi.com/t5/Desktop/DataFormat-Error-We-found-extra-characters-at-the-end-of-JSON/td-p/162013
https://community.powerbi.com/t5/Desktop/Sharepoint-We-found-extra-characters-at-the-end-of-JSON-input/td-p/755499
https://community.powerbi.com/t5/Power-Query/Cannot-connect-to-JSON-file-located-on-SharePoint/td-p/593845

**Comment by gulan28** [comment]
I've validated the `pivot.json` using JSLint and it says that it's a valid JSON. Reading through the links posted, it seems like there are some issues with Power BI's JSON parser. Are you able to load the CSV files ? `pivot.json` is simply a pivot table for all the different csv files.

Maybe you can paste `pivot.json` onto https://jsonlint.com/ and use the output ?

**Comment by codename062** [comment]
Let it be any issue.
It would be helpful if you you could make the data available in time_series format along with your current daily_reports format.
Reference: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data

**Comment by codename062** [comment]
Any way if you can make the format to match with that of the JHU or the mohfw.gov.in dataset format would be very helpful.
Country,State,District,Latitude,Longitude,Last Update Date/Time,Confirmed,Deaths,Recovered

**Comment by gulan28** [comment]
I've made changes to the `pivot_maker.py` script to create a timeseries csv as well. You can find it under `data/pivot.csv`.

**Comment by gulan28** [comment]
Closing this issue. you can find the timeseries csv under `/data/pivot.csv'

**Comment by codename062** [comment]
Do you know what is the data source for this?
https://map.coronasafe.in/
https://github.com/coronasafe/india-maps
Can you take a look at the data format?

**Comment by gulan28** [comment]
I'm sorry but this is for issues pertaining to this project only. You should try creating an issue on the project you have mentioned, if you  have any queries concerning `coronasafe` project.
