### ISSUE TITLE
Bug while selecting date of observation below March 8

### ISSUE THREAD

**Issue by gnoeee** [gulan28/covid19-viz#6]
After landing to the web-page and selecting any date before March 8, the website is crashing because of the rendering issues..

Don't know exact reason, but i think it is beacuse of the all values are '0' for all states.

I have forked and created a page for collecting the information and updating to Wikidata. So I have cleared all values to null so that the map shows only black background.

http://covid19.logitech.tech

**Comment by gulan28** [comment]
Sorry for the late reply. Issue was like you said, with the '0' for all states and `rmax` and `rmin` affected by those. I'll push a fix  for that

**Comment by gulan28** [comment]
Also, if you could link back to this project or mention it in credits, it would be great. I'm looking for volunteers as well to add more data and some regression on top of the data. It'd be great if you could spread the word. The work you've done on the fork looks cool 👍

**Comment by gnoeee** [comment]
Thanks for that.

Yup will add credits to both web page and github.
